# Generated by Django 3.0.3 on 2020-04-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='GGGtitle',
        ),
    ]
