# Generated by Django 3.0.3 on 2020-04-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200409_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='GGGtitle',
            new_name='title',
        ),
    ]
