# Generated by Django 3.0.3 on 2020-04-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200409_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imgUrl',
            new_name='image',
        ),
    ]
